format = """
$username\
$directory\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$docker_context
$character
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#ffffff"
format = '[$user ]($style)'

[directory]
style = "fg:#ffffff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "fg:#ffffff"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:#ffffff"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "fg:#ffffff"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:#ffffff"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#ffffff"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#ffffff"
format = '[$all_status$ahead_behind ]($style)'
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[golang]
symbol = " "
style = "fg:#ffffff"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:#ffffff"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:#ffffff"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:#ffffff"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#ffffff"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "fg:#ffffff"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#ffffff"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#ffffff"
format = '[ $time ]($style)'

[character]
success_symbol = " [](#ffffff)"
error_symbol = " [](#df5b61)"
vicmd_symbol = "[  ](#78b892)"
